### ISSUE TITLE
v0.23.1 install broken on OS X

### ISSUE THREAD

**Issue by lbighetti** [marciogm/asdf-crystal#4]
0.23.1 won't install on OSX - I'm using 0.23.0 as a workaround (this works).
See printscreen attached.

I can reproduce, let me know if you need anything else.

![image](https://user-images.githubusercontent.com/2095914/28778684-b44141c8-7600-11e7-9e77-99fce2c23f99.png)

**Comment by marciogm** [comment]
@lbighetti I just pushed to [fix_releases_url](/marciogm/asdf-crystal/tree/fix_releases_url).
From Travis, everything seems right. Can you test, please? before I can merge in master

**Comment by jeffhertzler** [comment]
The default macOS grep is FreeBSD grep. It doesn't support the -P flag.

**Comment by lbighetti** [comment]
Hi @marciogm, sorry I only had the time now.
Thanks a lot for the PR and also @jeffhertzler.

It however, still doesn't work for me:
![image](https://user-images.githubusercontent.com/2095914/28952319-a2352508-78d0-11e7-8336-818437aef7bc.png)

Let me know if I should open a new issue.
Thanks!

**Comment by marciogm** [comment]
@lbighetti curl is trying to resume the download. 
Try to delete the temp file and install again.
`rm /var/folders/wl/9........../T/crystal-0.23.1-version.tar.gz`

**Comment by lbighetti** [comment]
@marciogm thanks! you're right. After removing the file i was able to install.
I'm getting this now
`crystal -v`
>[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
>Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

have you seen this before, any idea how to fix ?

**Comment by marciogm** [comment]
@lbighetti 👍 
never, but I found it: https://github.com/spyder-ide/spyder/issues/3730
Seems to be an issue with `libevent`
you can try `export EVENT_NOKQUEUE=1` and test again :)

**Comment by lbighetti** [comment]
@marciogm wizard, that worked!

I get correct output now from `crystal -v`
>Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

Still... I'm getting a issue when trying to run crystal files though.
for example, When I try to run the basic http server hello world from Crystal website:

```crystal
# A very basic HTTP server
require "http/server"

server = HTTP::Server.new(8080) do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world, got #{context.request.path}!"
end

puts "Listening on http://127.0.0.1:8080"
server.listen
```

I get 
>Error in app.cr:1: while requiring "prelude": can't find file 'prelude' relative to >'/Users/leandro/ws/littlealchemist.io/exploring/crystal'
>
>require "http/server"
>^

The path `/Users/leandro/ws/littlealchemist.io/exploring/` is the root of the project. It seems like it's expecting a `crystal` folder with Crystal source code ?

Because this file is here: https://github.com/crystal-lang/crystal/tree/master/src

or perhaps i need an environment variable linking to crystal asdf installation ?

Thanks a lot!

**Comment by marciogm** [comment]
@lbighetti Yes, you're right! Thank You. 😄 
[asdf-crystal/commit/a43bb4f0272bf3876b7f9397702b27b9efd84c76](https://github.com/marciogm/asdf-crystal/commit/a43bb4f0272bf3876b7f9397702b27b9efd84c76)
Should work now 👍

**Comment by marciogm** [comment]
I changed the list-all too, but without luck.
It is failing on Travis again, I don't know why

**Comment by lbighetti** [comment]
Great! Works like a charm now!
Thanks a bunch @marciogm ! Really appreciate the help! 🙏

**Comment by marciogm** [comment]
Good, Glad to know! 😄
